### PR TITLE
Fix arrow-key scrolling while game is paused

### LINKED ISSUE #40: Free view moves strangely if the game is paused
Start a record (of a large scenario)
pause the game
press the left arrow key -> the camera moves to the left
press the right arrow key -> the camera continues to move to the left, then slows down and moves to the right
the up and down keys move the camera diagonally

### PR DESCRIPTION
**Pull request by Cyprex**
Previously FreeScroll() checked Game.FrameCounter to see if it is being called repetitively(i. e. the key is most likely pressed down). This does not work when the game is paused, as Game.FrameCounter does not increase. This PR replaces it with a C4Cooldown.
I chose 100 ms arbitrarily as it's close(a bit less) to what the game used previously and was low enough to not trigger when I pressed the key as fast as I could(users may want to do this to nudge the viewport precisely for a screenshot)

I've tested this, debug logging is in the first commit.

Fixes #40

### CODE REVIEW

**Comment by Cyprex** [comment]
A few things to note: If the original code seems confusing I could rename variables and/or add comments.
Additionally, I'm not sure if this function should even be in C4GraphicsSystem, maybe C4Viewport is appropriate? The way the scrolling vector is increased doesn't make scrolling feel great imo.

File: src/C4GraphicsSystem.h [hunk 1]
```diff
@@ -50,6 +51,8 @@ class C4GraphicsSystem
 	uint32_t dwGamma[C4MaxGammaRamps * 3]; // gamma ramps
 	bool fSetGamma; // must gamma ramp be reassigned?
 	C4LoaderScreen *pLoaderScreen;
+	//used to determine if arrow keys are held in FreeScroll()
+	C4Cooldown<std::chrono::milliseconds::rep, std::chrono::milliseconds::period> MostRecentScrolling{std::chrono::milliseconds{100}};
```
Comment (Cyprex) [inline src/C4GraphicsSystem.h:55]: there's probably a better way to name this than "MostRecentScrolling".
